"""OutcomeGraphCompiler — Level 1: DAG.yaml to LangGraph StateGraph.

Orchestrates: parse -> validate -> resolve -> build -> wire -> compile.
Deterministic: same DAG.yaml always produces the same StateGraph.
"""

from __future__ import annotations

import logging
import time
from typing import Any

from langgraph.graph import END, START, StateGraph
from langgraph.graph.state import CompiledStateGraph
from langgraph.types import Send

from sulis_workflows._tracing import span_context
from sulis_workflows.compiler.dag_parser import DAGParser, ParsedDAG
from sulis_workflows.compiler.graph_validator import GraphValidator
from sulis_workflows.compiler.metrics import get_compiler_metrics
from sulis_workflows.compiler.node_resolver import NodeResolver
from sulis_workflows.compiler.nodes.routing import make_routing_edge
from sulis_workflows.compiler.ports.spec_repository import SpecRepository
from sulis_workflows.compiler.state import OFMGraphState

logger = logging.getLogger(__name__)


class OutcomeGraphCompiler:
    """Compiles a DAG.yaml into a LangGraph StateGraph."""

    def __init__(self, spec_repo: SpecRepository) -> None:
        self._spec_repo = spec_repo
        self._parser = DAGParser()
        self._validator = GraphValidator()
        self._resolver = NodeResolver(spec_repo)

    def compile(self, outcome_id: str, *, checkpointer: Any | None = None) -> CompiledStateGraph:
        metrics = get_compiler_metrics()

        with span_context("compiler.compile", attributes={"outcome_id": outcome_id}) as span:
            start = time.monotonic()
            logger.info("Compiling outcome: %s", outcome_id)

            # 1. Load and parse
            dag_spec = self._spec_repo.load_dag(outcome_id)
            dag = self._parser.parse(dag_spec)

            # 2. Validate
            self._validator.validate(dag)

            # 3. Build StateGraph
            graph = StateGraph(OFMGraphState)

            # 4. Add nodes
            for node in dag.nodes:
                if node.type == "fan_out":
                    node_fn = self._resolver.resolve(node)
                    graph.add_node(node.id, node_fn)
                else:
                    node_fn = self._resolver.resolve(node)
                    graph.add_node(node.id, node_fn)

            # 5. Wire edges
            self._wire_edges(graph, dag)

            # 6. Set entry point
            roots = [n for n in dag.nodes if not n.depends_on]
            if len(roots) == 1:
                graph.set_entry_point(roots[0].id)
            else:
                for root in roots:
                    graph.add_edge(START, root.id)

            # 7. Compile
            compiled = graph.compile(checkpointer=checkpointer)

            elapsed = (time.monotonic() - start) * 1000
            span.set_attribute("compilation_time_ms", elapsed)
            span.set_attribute("node_count", len(dag.nodes))
            metrics.record_compilation_time(outcome_id, elapsed)
            logger.info(
                "Compiled outcome: %s in %.1fms (%d nodes)",
                outcome_id,
                elapsed,
                len(dag.nodes),
            )

            return compiled

    def compile_from_spec(
        self, dag_spec: dict, *, checkpointer: Any | None = None
    ) -> CompiledStateGraph:
        """Compile a DAG from a pre-built spec dict (no spec_repo lookup).

        Used by IntentGraphCompiler when the DAG spec is generated by LLM
        rather than loaded from a file.
        """
        metrics = get_compiler_metrics()

        with span_context("compiler.compile_from_spec", attributes={"source": "llm"}):
            start = time.monotonic()
            logger.info("Compiling from spec (no outcome_id)")

            dag = self._parser.parse(dag_spec)
            self._validator.validate(dag)

            graph = StateGraph(OFMGraphState)

            for node in dag.nodes:
                node_fn = self._resolver.resolve(node)
                graph.add_node(node.id, node_fn)

            self._wire_edges(graph, dag)

            roots = [n for n in dag.nodes if not n.depends_on]
            if len(roots) == 1:
                graph.set_entry_point(roots[0].id)
            else:
                for root in roots:
                    graph.add_edge(START, root.id)

            compiled = graph.compile(checkpointer=checkpointer)

            elapsed = (time.monotonic() - start) * 1000
            metrics.record_compilation_time("_from_spec", elapsed)
            logger.info("Compiled from spec in %.1fms (%d nodes)", elapsed, len(dag.nodes))

            return compiled

    def _wire_edges(self, graph: StateGraph, dag: ParsedDAG) -> None:
        successor_map = dag.get_successor_map()

        for node in dag.nodes:
            successors = successor_map.get(node.id, [])

            if not successors:
                graph.add_edge(node.id, END)
            elif len(successors) == 1:
                graph.add_edge(node.id, successors[0])
            else:
                if node.type == "routing":
                    routes = node.config.get("routes", {})
                    route_key = node.config.get("route_key", "route")
                    edge_fn = make_routing_edge(node.id, routes, route_key)
                    graph.add_conditional_edges(node.id, edge_fn)
                else:
                    # Fan-out: dispatch to all successors in parallel
                    self._add_fanout_edges(graph, node.id, successors)

    def _add_fanout_edges(self, graph: StateGraph, node_id: str, targets: list[str]) -> None:
        def fanout_router(state: dict) -> list[Send]:
            return [Send(target, state) for target in targets]

        graph.add_conditional_edges(node_id, fanout_router)
